apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping-container
        image: yourdockerhub/shopping-app:latest
        ports:
        - containerPort: 5000
